
server:
    port: 8083
spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        password: password
        url: jdbc:mysql://mysql-standalone:3306/courts?zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=UTC
        username: sa
    jpa:
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        hibernate:
            ddl-auto: update
 eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
